version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  product-service:
    build:
      context: ./product-service
    ports:
      - "5002:5002"
    depends_on:
      - mongo

  cart-service:
    build:
      context: ./cart-service
    ports:
      - "5003:5003"
    depends_on:
      - mongo

  order-service:
    build:
      context: ./order-service
    ports:
      - "5004:5004"
    depends_on:
      - mongo

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "5005:5005"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - cart-service
      - order-service
      - payment-service

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - product-service
      - cart-service
      - order-service
      - payment-service

volumes:
  mongo-data:
